Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,12 +16,23 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Install Qt
+      - name: Download Qt Installer
         run: |
           curl -Lo qt-installer.exe https://download.qt.io/official_releases/qt/5.15/5.15.2/qt-opensource-windows-x86-5.15.2.exe
+          if (!(Test-Path -Path "qt-installer.exe")) {
+            Write-Error "Qt installer download failed."
+            exit 1
+          }
+
+      - name: Verify Download
+        run: |
+          Get-FileHash qt-installer.exe
+
+      - name: Install Qt
+        run: |
           .\qt-installer.exe --script qt-installer-noninteractive.qs
 
-      - name: Verify directory structure 
+      - name: Verify directory structure
         run: dir /s /b tictactoegui
 
       - name: Build project
